language: ruby
env:
  - CODECLIMATE_REPO_TOKEN=fa06aacd1980b6ab831f5857ef588c3296c0c13287314596abccaa72e81c3d57
rvm:
  # - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - rbx-2.2
before_install:
  - curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.tar.gz | tar xz -C /tmp
before_script:
  - TEST_CLUSTER_COMMAND="/tmp/elasticsearch-1.2.1/bin/elasticsearch" bundle exec rake elasticsearch:start
